version: '3.5'

services:
  springboot-app:
    image: trainingimage
    #restart: always
    ports:
      - 8000:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trainingdb